swagger: '2.0'
info:
  description: >-
    Simple api allows qorus receive messages from an IoT event source
  version: 1.0.0
  title: IoT stadium floodlights
  contact:
    email: support@qoretechnologies.com
host: localhost #https://cloud1.qoretechnologies.com:8011
basePath: /iot
paths:
  '/stadium-floodlights':
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: msg
          required: true
          schema:
            $ref: '#/definitions/Msg'
      responses:
        201:
          description: Received
          schema:
            type: string
        409:
          description: Duplicate
          schema:
            type: string
definitions:
  Msg:
    description: Received msg
    type: object
    required:
      - device_id
      - stadium_id
    properties:
      request_id:
        type: string
      device_id:
        type: string
      stadium_id:
        type: string