vscode:
  extensions:
    - qoretechnologies.qore-vscode
tasks:
  - init: |
      npm install
    command: |
      git config --global http.sslverify false
      cd /workspace/qorus-vscode
      cd frontend
      yarn install
      yarn install-playwright
      yarn storybook
ports:
  - port: 3140-3199
    visibility: private
#additionalRepositories:
#- url: https://git.qoretechnologies.com/qorus/demos.git
#- url: https://git.qoretechnologies.com/qorus/qorus.git
