vscode:
  extensions:
    - oderwat.indent-rainbow
    - mintlify.document
    - streetsidesoftware.code-spell-checker
    - tombonnike.vscode-status-bar-format-toggle
    - github.copilot
    - fivepointseven.node-version
    - kejun.devtoys
    - esbenp.prettier-vscode
    - visualstudioexptteam.vscodeintellicode
    - styled-components.vscode-styled-components
    - kejun.devtoys
    - qoretechnologies.qore-vscode
tasks:
  - init: |
      nvm install v14.18
      npm install
      cd /workspace
      git clone https://git.qoretechnologies.com/qorus/building-blocks
    command: |
      nvm install v14.18
      git config --global http.sslverify false
      npm run start
