tasks:
  - init: |
      yarn install
    command: |
      git config --global http.sslverify false
      cd /workspace/qorus-ide
      yarn install
      yarn install-playwright
      yarn storybook
ports:
  - port: 3140-3199
    visibility: private
  - port: 6006
    visibility: public
