vscode:
  extensions:
    - qoretechnologies.qore-vscode
tasks:
  - init: |
      yarn install
    command: |
      git config --global http.sslverify false
      cd /workspace/qorus-vscode
      yarn start
ports:
  - port: 3140-3199
    visibility: private
additionalRepositories:
  - url: https://git.qoretechnologies.com/qorus/demos.git
  - url: https://git.qoretechnologies.com/qorus/qorus.git
