# This is a generated file, don't edit!
type: class
name: DifferentConfigItems
desc: asg
lang: python
version: '1'
code: DifferentConfigItems-1.qclass.py
config-items:
  - name: SomeConfigItem
    default_value:
        "asgf"
    description: asg
    config_group: asg
