# This is a generated file, don't edit!
type: class
name: ServiceClassWithConfigItems
desc: Test service class with config items
lang: qore
version: "1.2"
base-class-name: QorusService
code: ServiceClassWithConfigItems-1.2.qclass
config-items:
  - name: test-config-item-1
    default_value:
        54
    description: test config item of a base class
    config_group: test
    type: int
    allowed_values:
      - 54
